services:
  eleventy:
    image: femtopixel/eleventy
    volumes:
      - "./:/var/www"
    working_dir: "/var/www"
    entrypoint: []
  server:
    image: femtopixel/eleventy
    command: --serve
    volumes:
      - "./:/var/www"
    working_dir: "/var/www"
    ports:
      - "80:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENVIRONMENT=development
